name: fem
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.2.1
  weather: ^3.1.1
  intl: ^0.18.1
  weather_icons: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/gis_image.jpeg
    - assets/animations/
    - assets/pictures/
